language: minimal

before-install:
  - sudo apt-get update
  - sudo apt-get -y install xsltproc

script:
  - curl https://raw.githubusercontent.com/TEIC/CETEIcean/master/xslt/make-CETEIcean.xsl -o make-CETEIcean.xsl
  - git clone https://github.com/TEIC/teic.github.io.git
  - ./bin/publish.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master