name: Publish TEI Council Documentation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: master
        path: main
    - name: Install libxml2-utils
      run: sudo apt-get update && sudo apt-get install libxml2-utils xsltproc
    - name: transform XML
      run: bash main/bin/publish.sh
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push