name: Publish TEI Council Documentation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Install libxml2-utils
      run: sudo apt-get update && sudo apt-get install libxml2-utils xsltproc
    - name: transform XML
      run: bash bin/publish.sh